apiVersion: v1
kind: Pod
metadata:
  name: liveness-mybusapp
spec:
  containers:
  - args:
    - /server
    image: gcr.io/google_containers/liveness
    livenessProbe:
      httpGet:
        path: /health-check
        port: 5000
      initialDelaySeconds: 15
      timeoutSeconds: 5
    name: mybusapp
