apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 3
    labels:
      app: mybusapp
    name: mybusapp
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: mybusapp
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: mybusapp
      spec:
        containers:
        - image: gcr.io/YOURGCEPROJECTIDENTIFIER/mybusservice:latest
          imagePullPolicy: Always
          name: mybusapp
          resources: {}
          terminationMessagePath: /dev/termination-log
          livenessProbe:
            httpGet:
              path: /health-check
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 5
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    observedGeneration: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata: {}
