apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "3"
      deployment.kubernetes.io/max-replicas: "4"
      deployment.kubernetes.io/revision: "1"
    generation: 2
    labels:
      run: mybusapp
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        run: mybusapp
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: mybusapp
      spec:
        containers:
        - image: gcr.io/stellar-forest-96608/mybusservice:latest
          imagePullPolicy: Always
          name: mybusapp
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    fullyLabeledReplicas: 3
    observedGeneration: 2
    replicas: 3
kind: List
metadata: {}
